image: python:3.6-alpine

stages:
  - deploy

before_script:
   - apk add git
   - pip install twine

deploy_staging:
  stage: deploy
  tags:
    - waterrat-tag
  variables:
    GIT_USER: $STAGING_USERNAME
    GIT_PASS: $STAGING_PASSWORD
    GIT_EMAIL: $STAGING_EMAIL
  script:
    - git config --global user.name $GIT_USER
    - git config --global user.email $GIT_EMAIL
    - git clone https://$GIT_USER:$GIT_PASS@github.com/bhuffman-usgs/waterrat.git
    - cd WaterRat
    - ls | grep -v .git | xargs rm -rf
    - cp -r ../docs .
    - cp -r ../waterrat .
    - cp ../License.md .
    - cp ../MANIFEST.in .
    - cp ../README.md .
    - cp ../setup.py .
    - cp ../config.ini .
    - git add .
    - git commit -m "update repo"
    - git push
  except:
    - tags

deploy_production:
  stage: deploy
  tags:
    - waterrat-tag
  variables:
    TWINE_USERNAME: $PRODUCTION_USERNAME
    TWINE_PASSWORD: $PRODUCTION_PASSWORD
  script:
    - python setup.py sdist
    - twine upload dist/*
  only:
    - tags